objectid,proyecto,estado,mensaje
7,"Guardianes de la Sierra: Convivencia, Territorio Seguro y Desarrollo Integral",ERROR,"✖ Error en proyecto 7 - Guardianes de la Sierra: Convivencia, Territorio Seguro y Desarrollo Integral: Error general: ERROR 002869: Output file memory\Proyectos_Inversion already exists.
Failed to execute (CreateFeatureclass).

Traceback (most recent call last):
  File ""C:\Users\Sebastian\Documents\GitHub\SimuladorProyectosInversion\SimuladorGP.py"", line 62, in script_tool
    arcpy.CreateFeatureclass_management(""memory"", ""Proyectos_Inversion"",
  File ""C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py"", line 5764, in CreateFeatureclass
    raise e
  File ""C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py"", line 5741, in CreateFeatureclass
    gp.CreateFeatureclass_management(
  File ""C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py"", line 533, in <lambda>
    return lambda *args: val(*gp_fixargs(args, True))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
arcgisscripting.ExecuteError: ERROR 002869: Output file memory\Proyectos_Inversion already exists.
Failed to execute (CreateFeatureclass).


Failed to execute (CICLO1).
"
1,Mujeres Impulsando Futuro: Liderazgo y Emprendimiento con Equidad,ERROR,"✖ Error en proyecto 1 - Mujeres Impulsando Futuro: Liderazgo y Emprendimiento con Equidad: Error general: ERROR 160326: The table already exists.
Failed to execute (CreateFeatureclass).

Traceback (most recent call last):
  File ""C:\Users\Sebastian\Documents\GitHub\SimuladorProyectosInversion\SimuladorGP.py"", line 62, in script_tool
    arcpy.CreateFeatureclass_management(""memory"", ""Proyectos_Inversion"",
  File ""C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py"", line 5764, in CreateFeatureclass
    raise e
  File ""C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py"", line 5741, in CreateFeatureclass
    gp.CreateFeatureclass_management(
  File ""C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py"", line 533, in <lambda>
    return lambda *args: val(*gp_fixargs(args, True))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
arcgisscripting.ExecuteError: ERROR 160326: The table already exists.
Failed to execute (CreateFeatureclass).


Failed to execute (CICLO1).
"
8,"Guardianes de la Sierra: Convivencia, Territorio Seguro y Desarrollo Integral",ERROR,"✖ Error en proyecto 8 - Guardianes de la Sierra: Convivencia, Territorio Seguro y Desarrollo Integral: Error general: ERROR 002869: Output file memory\Proyectos_Inversion already exists.
Failed to execute (CreateFeatureclass).

Traceback (most recent call last):
  File ""C:\Users\Sebastian\Documents\GitHub\SimuladorProyectosInversion\SimuladorGP.py"", line 62, in script_tool
    arcpy.CreateFeatureclass_management(""memory"", ""Proyectos_Inversion"",
  File ""C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py"", line 5764, in CreateFeatureclass
    raise e
  File ""C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py"", line 5741, in CreateFeatureclass
    gp.CreateFeatureclass_management(
  File ""C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py"", line 533, in <lambda>
    return lambda *args: val(*gp_fixargs(args, True))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
arcgisscripting.ExecuteError: ERROR 002869: Output file memory\Proyectos_Inversion already exists.
Failed to execute (CreateFeatureclass).


Failed to execute (CICLO1).
"
2,Mujeres Impulsando Futuro: Liderazgo y Emprendimiento con Equidad,ERROR,"✖ Error en proyecto 2 - Mujeres Impulsando Futuro: Liderazgo y Emprendimiento con Equidad: Error general: ERROR 160326: The table already exists.
Failed to execute (CreateFeatureclass).

Traceback (most recent call last):
  File ""C:\Users\Sebastian\Documents\GitHub\SimuladorProyectosInversion\SimuladorGP.py"", line 62, in script_tool
    arcpy.CreateFeatureclass_management(""memory"", ""Proyectos_Inversion"",
  File ""C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py"", line 5764, in CreateFeatureclass
    raise e
  File ""C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py"", line 5741, in CreateFeatureclass
    gp.CreateFeatureclass_management(
  File ""C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py"", line 533, in <lambda>
    return lambda *args: val(*gp_fixargs(args, True))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
arcgisscripting.ExecuteError: ERROR 160326: The table already exists.
Failed to execute (CreateFeatureclass).


Failed to execute (CICLO1).
"
9,"Guardianes de la Sierra: Convivencia, Territorio Seguro y Desarrollo Integral",ERROR,"✖ Error en proyecto 9 - Guardianes de la Sierra: Convivencia, Territorio Seguro y Desarrollo Integral: Error general: ERROR 160326: The table already exists.
Failed to execute (CreateFeatureclass).

Traceback (most recent call last):
  File ""C:\Users\Sebastian\Documents\GitHub\SimuladorProyectosInversion\SimuladorGP.py"", line 62, in script_tool
    arcpy.CreateFeatureclass_management(""memory"", ""Proyectos_Inversion"",
  File ""C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py"", line 5764, in CreateFeatureclass
    raise e
  File ""C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py"", line 5741, in CreateFeatureclass
    gp.CreateFeatureclass_management(
  File ""C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py"", line 533, in <lambda>
    return lambda *args: val(*gp_fixargs(args, True))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
arcgisscripting.ExecuteError: ERROR 160326: The table already exists.
Failed to execute (CreateFeatureclass).


Failed to execute (CICLO1).
"
10,Vive Saludable: Salud Integral para Comunidades Resilientes,ERROR,"✖ Error en proyecto 10 - Vive Saludable: Salud Integral para Comunidades Resilientes: Error general: Failed to execute. Parameters are not valid.
ERROR 000732: Input Table: Dataset memory/Proyectos_Inversion does not exist or is not supported
Failed to execute (AddField).

Traceback (most recent call last):
  File ""C:\Users\Sebastian\Documents\GitHub\SimuladorProyectosInversion\SimuladorGP.py"", line 71, in script_tool
    arcpy.AddField_management(fc_path, name, ftype, field_length=length or """")
  File ""C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py"", line 7953, in AddField
    raise e
  File ""C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py"", line 7933, in AddField
    gp.AddField_management(
  File ""C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py"", line 533, in <lambda>
    return lambda *args: val(*gp_fixargs(args, True))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
arcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.
ERROR 000732: Input Table: Dataset memory/Proyectos_Inversion does not exist or is not supported
Failed to execute (AddField).


Failed to execute (CICLO1).
"
19,Sistema Integrado de Video Protección Ciudadana,ERROR,"✖ Error en proyecto 19 - Sistema Integrado de Video Protección Ciudadana: Error general: ERROR 000229: Cannot open 
Failed to execute (AddField).

Traceback (most recent call last):
  File ""C:\Users\Sebastian\Documents\GitHub\SimuladorProyectosInversion\SimuladorGP.py"", line 71, in script_tool
    arcpy.AddField_management(fc_path, name, ftype, field_length=length or """")
  File ""C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py"", line 7953, in AddField
    raise e
  File ""C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py"", line 7933, in AddField
    gp.AddField_management(
  File ""C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py"", line 533, in <lambda>
    return lambda *args: val(*gp_fixargs(args, True))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
arcgisscripting.ExecuteError: ERROR 000229: Cannot open 
Failed to execute (AddField).


Failed to execute (CICLO1).
"
21,Sistema Integrado de Video Protección Ciudadana,ERROR,"✖ Error en proyecto 21 - Sistema Integrado de Video Protección Ciudadana: Error general: Failed to execute. Parameters are not valid.
ERROR 000732: Input Table: Dataset memory/Proyectos_Inversion does not exist or is not supported
Failed to execute (AddField).

Traceback (most recent call last):
  File ""C:\Users\Sebastian\Documents\GitHub\SimuladorProyectosInversion\SimuladorGP.py"", line 71, in script_tool
    arcpy.AddField_management(fc_path, name, ftype, field_length=length or """")
  File ""C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py"", line 7953, in AddField
    raise e
  File ""C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py"", line 7933, in AddField
    gp.AddField_management(
  File ""C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py"", line 533, in <lambda>
    return lambda *args: val(*gp_fixargs(args, True))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
arcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.
ERROR 000732: Input Table: Dataset memory/Proyectos_Inversion does not exist or is not supported
Failed to execute (AddField).


Failed to execute (CICLO1).
"
11,Vive Saludable: Salud Integral para Comunidades Resilientes,ERROR,"✖ Error en proyecto 11 - Vive Saludable: Salud Integral para Comunidades Resilientes: Error general: Cannot find field 'PROYECTO'
Traceback (most recent call last):
  File ""C:\Users\Sebastian\Documents\GitHub\SimuladorProyectosInversion\SimuladorGP.py"", line 82, in script_tool
    ic.insertRow([(g[""longitude""], g[""latitude""]),
RuntimeError: Cannot find field 'PROYECTO'

Failed to execute (CICLO1).
"
20,Sistema Integrado de Video Protección Ciudadana,ERROR,"✖ Error en proyecto 20 - Sistema Integrado de Video Protección Ciudadana: Error general: Cannot find field 'PROJECT_ID'
Traceback (most recent call last):
  File ""C:\Users\Sebastian\Documents\GitHub\SimuladorProyectosInversion\SimuladorGP.py"", line 82, in script_tool
    ic.insertRow([(g[""longitude""], g[""latitude""]),
RuntimeError: Cannot find field 'PROJECT_ID'

Failed to execute (CICLO1).
"
23,Conexiones Vitales: Infraestructura Vial para el Desarrollo Regional,ERROR,"✖ Error en proyecto 23 - Conexiones Vitales: Infraestructura Vial para el Desarrollo Regional: Error general: Failed to execute. Parameters are not valid.
ERROR 000732: Input Table: Dataset memory/Proyectos_Inversion does not exist or is not supported
Failed to execute (AddField).

Traceback (most recent call last):
  File ""C:\Users\Sebastian\Documents\GitHub\SimuladorProyectosInversion\SimuladorGP.py"", line 71, in script_tool
    arcpy.AddField_management(fc_path, name, ftype, field_length=length or """")
  File ""C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py"", line 7953, in AddField
    raise e
  File ""C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py"", line 7933, in AddField
    gp.AddField_management(
  File ""C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py"", line 533, in <lambda>
    return lambda *args: val(*gp_fixargs(args, True))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
arcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.
ERROR 000732: Input Table: Dataset memory/Proyectos_Inversion does not exist or is not supported
Failed to execute (AddField).


Failed to execute (CICLO1).
"
22,Conexiones Vitales: Infraestructura Vial para el Desarrollo Regional,ERROR,"✖ Error en proyecto 22 - Conexiones Vitales: Infraestructura Vial para el Desarrollo Regional: Error general: Cannot find field 'PROJECT_ID'
Traceback (most recent call last):
  File ""C:\Users\Sebastian\Documents\GitHub\SimuladorProyectosInversion\SimuladorGP.py"", line 82, in script_tool
    ic.insertRow([(g[""longitude""], g[""latitude""]),
RuntimeError: Cannot find field 'PROJECT_ID'

Failed to execute (CICLO1).
"
24,Conexiones Vitales: Infraestructura Vial para el Desarrollo Regional,ERROR,"✖ Error en proyecto 24 - Conexiones Vitales: Infraestructura Vial para el Desarrollo Regional: Error general: Cannot find field 'SEGURIDAD'
Traceback (most recent call last):
  File ""C:\Users\Sebastian\Documents\GitHub\SimuladorProyectosInversion\SimuladorGP.py"", line 82, in script_tool
    ic.insertRow([(g[""longitude""], g[""latitude""]),
RuntimeError: Cannot find field 'SEGURIDAD'

Failed to execute (CICLO1).
"
12,Vive Saludable: Salud Integral para Comunidades Resilientes,ERROR,"✖ Error en proyecto 12 - Vive Saludable: Salud Integral para Comunidades Resilientes: Error general: Cannot find field 'TEAM_NAME'
Traceback (most recent call last):
  File ""C:\Users\Sebastian\Documents\GitHub\SimuladorProyectosInversion\SimuladorGP.py"", line 192, in script_tool
    ic.insertRow([tname, tcode,
RuntimeError: Cannot find field 'TEAM_NAME'

﻿ModuleNotFoundError: No module named 'BathymetryModel'

Failed to execute (CICLO1).
"
3,Mujeres Impulsando Futuro: Liderazgo y Emprendimiento con Equidad,OK,✔ Proyecto 3 - Mujeres Impulsando Futuro: Liderazgo y Emprendimiento con Equidad procesado correctamente
31,Gas para Todos: Expansión Sostenible del Servicio Domiciliario,OK,✔ Proyecto 31 - Gas para Todos: Expansión Sostenible del Servicio Domiciliario procesado correctamente
101,Escuelas Vivas: Red Educativa Rural para el Futuro,ERROR,"✖ Error en proyecto 101 - Escuelas Vivas: Red Educativa Rural para el Futuro: Error general: ERROR 000871: Output Raster: Unable to delete the output in_memory\R_seguridad_1_delta.
Traceback (most recent call last):
  File ""C:\Users\Sebastian\Documents\GitHub\SimuladorProyectosInversion\SimuladorGP.py"", line 124, in script_tool
    incremento.save(delta_path)
RuntimeError: ERROR 000871: Output Raster: Unable to delete the output in_memory\R_seguridad_1_delta.

Failed to execute (CICLO1).
"
103,Sierra Emprende: Fortalecimiento Empresarial y Comunitario con Enfoque Territorial,ERROR,"✖ Error en proyecto 103 - Sierra Emprende: Fortalecimiento Empresarial y Comunitario con Enfoque Territorial: Error general: ERROR 000871: Output Raster: Unable to delete the output in_memory\R_seguridad_1_delta.
Traceback (most recent call last):
  File ""C:\Users\Sebastian\Documents\GitHub\SimuladorProyectosInversion\SimuladorGP.py"", line 124, in script_tool
    incremento.save(delta_path)
RuntimeError: ERROR 000871: Output Raster: Unable to delete the output in_memory\R_seguridad_1_delta.

Failed to execute (CICLO1).
"
102,Escuelas Vivas: Red Educativa Rural para el Futuro,ERROR,"✖ Error en proyecto 102 - Escuelas Vivas: Red Educativa Rural para el Futuro: Error general: ERROR 000871: Output Raster: Unable to delete the output in_memory\R_seguridad_1_delta.
Traceback (most recent call last):
  File ""C:\Users\Sebastian\Documents\GitHub\SimuladorProyectosInversion\SimuladorGP.py"", line 124, in script_tool
    incremento.save(delta_path)
RuntimeError: ERROR 000871: Output Raster: Unable to delete the output in_memory\R_seguridad_1_delta.

Failed to execute (CICLO1).
"
32,Gas para Todos: Expansión Sostenible del Servicio Domiciliario,OK,✔ Proyecto 32 - Gas para Todos: Expansión Sostenible del Servicio Domiciliario procesado correctamente
100,Escuelas Vivas: Red Educativa Rural para el Futuro,OK,✔ Proyecto 100 - Escuelas Vivas: Red Educativa Rural para el Futuro procesado correctamente
113,Rutas de Confianza: Articulación Institucional para la Paz Local,ERROR,"✖ Error en proyecto 113 - Rutas de Confianza: Articulación Institucional para la Paz Local: Error general: Cannot find field 'SEGURIDAD'
Traceback (most recent call last):
  File ""C:\Users\Sebastian\Documents\GitHub\SimuladorProyectosInversion\SimuladorGP.py"", line 82, in script_tool
    ic.insertRow([(g[""longitude""], g[""latitude""]),
RuntimeError: Cannot find field 'SEGURIDAD'

Failed to execute (CICLO1).
"
112,Rutas de Confianza: Articulación Institucional para la Paz Local,ERROR,"✖ Error en proyecto 112 - Rutas de Confianza: Articulación Institucional para la Paz Local: Error general: ERROR 000871: Output Raster: Unable to delete the output in_memory\R_seguridad_1_delta.
Traceback (most recent call last):
  File ""C:\Users\Sebastian\Documents\GitHub\SimuladorProyectosInversion\SimuladorGP.py"", line 124, in script_tool
    incremento.save(delta_path)
RuntimeError: ERROR 000871: Output Raster: Unable to delete the output in_memory\R_seguridad_1_delta.

Failed to execute (CICLO1).
"
105,Sierra Emprende: Fortalecimiento Empresarial y Comunitario con Enfoque Territorial,ERROR,"✖ Error en proyecto 105 - Sierra Emprende: Fortalecimiento Empresarial y Comunitario con Enfoque Territorial: Error general: ERROR 000871: Output Raster: Unable to delete the output in_memory\R_seguridad_1_delta.
Traceback (most recent call last):
  File ""C:\Users\Sebastian\Documents\GitHub\SimuladorProyectosInversion\SimuladorGP.py"", line 124, in script_tool
    incremento.save(delta_path)
RuntimeError: ERROR 000871: Output Raster: Unable to delete the output in_memory\R_seguridad_1_delta.

Failed to execute (CICLO1).
"
104,Sierra Emprende: Fortalecimiento Empresarial y Comunitario con Enfoque Territorial,ERROR,"✖ Error en proyecto 104 - Sierra Emprende: Fortalecimiento Empresarial y Comunitario con Enfoque Territorial: Error general: ERROR 000871: Output Raster: Unable to delete the output in_memory\R_seguridad_1_delta.
Traceback (most recent call last):
  File ""C:\Users\Sebastian\Documents\GitHub\SimuladorProyectosInversion\SimuladorGP.py"", line 124, in script_tool
    incremento.save(delta_path)
RuntimeError: ERROR 000871: Output Raster: Unable to delete the output in_memory\R_seguridad_1_delta.

Failed to execute (CICLO1).
"
114,Rutas de Confianza: Articulación Institucional para la Paz Local,ERROR,"✖ Error en proyecto 114 - Rutas de Confianza: Articulación Institucional para la Paz Local: Error general: ERROR 000871: Output Raster: Unable to delete the output in_memory\R_seguridad_1_delta.
Traceback (most recent call last):
  File ""C:\Users\Sebastian\Documents\GitHub\SimuladorProyectosInversion\SimuladorGP.py"", line 124, in script_tool
    incremento.save(delta_path)
RuntimeError: ERROR 000871: Output Raster: Unable to delete the output in_memory\R_seguridad_1_delta.

Failed to execute (CICLO1).
"
33,Gas para Todos: Expansión Sostenible del Servicio Domiciliario,OK,✔ Proyecto 33 - Gas para Todos: Expansión Sostenible del Servicio Domiciliario procesado correctamente
